networks:
  demoblazorapp:

services:
  backoffice:
    container_name: app-backoffice
    build:
      context: .
      dockerfile: Backoffice/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://+:8080
      - Kestrel__EndPoints__Http__Url=http://+:8080
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    ports:
      - "3001:8080"
      # - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - demoblazorapp 

  demoappdb:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - demoblazorapp
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata: